In [1]:
from decision_tree import decision_tree
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
data = pd.read_csv("zoo.csv", header=None)
x_data = data.iloc[:, 1:-1].values.tolist()
y_data = data.iloc[:, -1].values.tolist()
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.2, random_state=33)
data.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,aardvark,1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1,1
1,antelope,1,0,0,1,0,0,0,1,1,1,0,0,4,1,0,1,1
2,bass,0,0,1,0,0,1,1,1,1,0,0,1,0,1,0,0,4
3,bear,1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1,1
4,boar,1,0,0,1,0,0,1,1,1,1,0,0,4,1,0,1,1

In [3]:
criterions = ["entropy", "gini"]

for cr in criterions:
    dt = decision_tree(criterion=cr)
    dt.fit(x_train,y_train)
    hyp = dt.predict(x_test)
    print("====================================")
    print("Result for {0}:".format(cr))
    print("prediction:", hyp)
    print("y_test:", y_test)
    print("accuracy:", accuracy_score(hyp, y_test))

====================================
Result for entropy:
prediction: [2, 1, 1, 4, 2, 2, 1, 3, 7, 1, 6, 4, 1, 4, 2, 2, 2, 2, 1, 2, 2]
y_test: [2, 1, 1, 4, 2, 2, 1, 5, 7, 1, 6, 4, 1, 4, 2, 2, 2, 2, 1, 2, 2]
accuracy: 0.952380952381
====================================
Result for gini:
prediction: [2, 1, 1, 4, 2, 2, 1, 3, 7, 1, 6, 4, 1, 4, 2, 2, 2, 2, 1, 2, 2]
y_test: [2, 1, 1, 4, 2, 2, 1, 5, 7, 1, 6, 4, 1, 4, 2, 2, 2, 2, 1, 2, 2]
accuracy: 0.952380952381